---
title: "POLS 206 Final Project"
author: "Cori Lopazanski"
date: "Due 3/17/2021"
output: html_document
---

```{r setup and basic wrangling, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,	warning = FALSE)

############################################
### Attach Packages & Read Data
############################################
library(tidyverse)
library(janitor)
library(stargazer)
library(MASS)
library(car)
library(lubridate)
library(emmeans)
library(glmmTMB)

folpp <- read_csv("folpp-data-raw.csv") %>% clean_names()

############################################
### Basic Wrangling
############################################
folpp_clean <- folpp %>% 
  filter(season != "Aut") %>% 
  mutate(before_after = factor(before_after, levels = c("Before", "After")), # arange before/after factor levels
         sample_period = factor(case_when(year == 1 ~ "Before",
                                             year == 2 ~ "After 1",
                                             year == 3 ~ "After 2"),
                                levels = c("Before", "After 1", "After 2")),
         reef_type = factor(case_when(habitat == "SD" ~ "AR", # sand habitat eventually became artificial reef
                                      habitat == "AR" ~ "AR", # artificial reef
                                      habitat == "NR" ~ "NR"), # natural reef
                            levels = c("AR", "NR")), # rename and convert to factor to match paper wording
         site = as.factor(paste(location, site2)), # rename to match wording in paper
         time2 = mdy(time), # use lubridate to convert to date format
         estuary = location) # rename to match wording in paper

```

### Methods

This project replicates the data analysis conducted in Folpp et al. 2020, which examines changes in fish abundance in three habitat-limited estuaries after adding artificial reef structures. Sampling was conducted at six artificial reef sites and three natural control sites in each estuary over three years: before the artificial reefs were deployed, one year post-deployment, and two years post-deployment. Each site was sampled six times within the same three-month period. Fish abundance was measured by quantifying the maximum number of each species observed simultaneously (MaxN) during 30-minute baited remote underwater videos (BRUV).

Folpp et al. 2020 notes that three artificial reef sites in each estuary were not sampled before artificial reef deployment because of uncertainty in deployment locations, and two of the six artificial reef sites in Botany Bay were excluded from the study due to high levels of sedimentation after deployment. 



### References

Folpp, H.R., Schilling, H.T., Clark, G.F., Lowry, M.B., Maslen, B., Gregson, M., Suthers, I.M., 2020. Artificial reefs increase fish abundance in habitat-limited estuaries. Journal of Applied Ecology 57, 1752–1761. https://doi.org/10.1111/1365-2664.13666
